kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud
  role: pingdatasync

resources:
- ../../../../base/pingdatasync/config

configMapGenerator:
- name: pingdatasync-environment-variables
  behavior: merge
  envs:
  - env_vars
