apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "ping-cloud-${CLUSTER_STATE_REPO_BRANCH}-${TENANT_NAME}-${REGION_NICK_NAME}"
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/git-branch: ${CLUSTER_STATE_REPO_BRANCH}
    argocd-image-updater.argoproj.io/image-list: ${IMAGE_LIST}
    argocd-image-updater.argoproj.io/apps.update-strategy: latest
    argocd-image-updater.argoproj.io/apps.allow-tags: regexp:^${IMAGE_TAG_PREFIX}.[0-9]+$
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-ssh-key
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    notifications.argoproj.io/subscribe.on-sync-failed.slack: ${SLACK_CHANNEL}
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: ${SLACK_CHANNEL}
spec:
  generators:
    - git:
        repoURL: ${CLUSTER_STATE_REPO_URL}
        revision: ${CLUSTER_STATE_REPO_BRANCH}
        directories:
          - path: ${REGION_NICK_NAME}/*
  template:
    metadata:
      name: '${REGION_NICK_NAME}-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: ${CLUSTER_STATE_REPO_URL}
        targetRevision: ${CLUSTER_STATE_REPO_BRANCH}
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
      ignoreDifferences:
        - group: batch
          kind: Job
          jsonPointers:
            - /spec/ttlSecondsAfterFinished
      syncPolicy:
        automated:
          prune: true