kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ping-cloud

commonLabels:
  app: ping-cloud
  role: pingfederate-admin-configurator

generatorOptions:
  disableNameSuffixHash: true

resources:
- job.yaml
- rbac.yaml