#
# This service exposes the pingfederate runtime ports to the cluster.
#
apiVersion: v1
kind: Service
metadata:
  name: pingfederate
spec:
  ports:
  - port: 9031
    name: pingfederate-runtime
  - port: 8080
    name: metrics
  - port: 8079
    name: pf-heartbeat
  selector:
    role: pingfederate-engine
