### Deploy the git key of the CD tool to the cluster state repo ###
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: argo-git-deploy
  namespace: argocd
data:
  identity: |
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNBbE1LcThyUUFSaE5LcnlKVUQwN2JxMVJJNW01bFFkYTQ4M1l6U3F5Y2daUUFBQUtBeFRGZ3BNVXhZCktRQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQWxNS3E4clFBUmhOS3J5SlVEMDdicTFSSTVtNWxRZGE0ODNZelNxeWNnWlEKQUFBRUIvdExWVG5OQXFxZ3ROV2pRRzJRYkZjOGFpOWhIQm9yVXZlMXlEalFnWjd5VXdxcnl0QUJHRTBxdklsUVBUdHVyVgpFam1ibVZCMXJqemRqTktySnlCbEFBQUFIRzl6WTJGeVpteHZjbVZ6UUhCcGJtZHBaR1Z1ZEdsMGVTNWpiMjBCCi0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo=

---

### Ping app SSH private key ###

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ssh-id-key-secret
data:
  id_rsa: |
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNBbE1LcThyUUFSaE5LcnlKVUQwN2JxMVJJNW01bFFkYTQ4M1l6U3F5Y2daUUFBQUtBeFRGZ3BNVXhZCktRQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQWxNS3E4clFBUmhOS3J5SlVEMDdicTFSSTVtNWxRZGE0ODNZelNxeWNnWlEKQUFBRUIvdExWVG5OQXFxZ3ROV2pRRzJRYkZjOGFpOWhIQm9yVXZlMXlEalFnWjd5VXdxcnl0QUJHRTBxdklsUVBUdHVyVgpFam1ibVZCMXJqemRqTktySnlCbEFBQUFIRzl6WTJGeVpteHZjbVZ6UUhCcGJtZHBaR1Z1ZEdsMGVTNWpiMjBCCi0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo=

---

# NewRelic license key to send APM data
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: newrelic-license-key
data:
  NEW_RELIC_LICENSE_KEY: dW51c2Vk

---
### Licenses ###

# Add PingDirectory.lic (case-sensitive) to the data section with the base64-encoded value of the license file
apiVersion: v1
kind: Secret
metadata:
  name: pingdirectory-license
type: Opaque

---

# Add pingfederate.lic (case-sensitive) to the data section with the base64-encoded value of the license file
apiVersion: v1
kind: Secret
metadata:
  name: pingfederate-license
type: Opaque

---

# Add pingaccess.lic (case-sensitive) to the data section with the base64-encoded value of the license file
apiVersion: v1
kind: Secret
metadata:
  name: pingaccess-license
type: Opaque

---

# Add pingaccess.lic (case-sensitive) to the data section with the base64-encoded value of the license file
apiVersion: v1
kind: Secret
metadata:
  name: pingaccess-was-license
type: Opaque

---

### Product passwords ###

# Supported keys:
# Exported as environment variables: PF_ADMIN_USER_PASSWORD, PF_LDAP_PASSWORD, DA_OAUTH_TOKEN_VALIDATOR_SECRET
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingcommon-passwords

---

# Supported keys:
# Mounted as files: root-user-password, admin-user-password, encryption-password, encryption-settings.pin, ads.crt, ads.key
# Exported as environment variables: P14C_ENVIRONMENT_ID, P14C_CLIENT_ID, P14C_CLIENT_SECRET
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingdirectory-passwords

---

# Supported keys:
# Exported as environment variables: PA_ADMIN_USER_PASSWORD, OLD_PA_ADMIN_USER_PASSWORD
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingaccess-passwords

---

# Supported keys:
# Exported as environment variables: PA_ADMIN_USER_PASSWORD, OLD_PA_ADMIN_USER_PASSWORD,
#                                    P14C_ISSUER, P14C_CLIENT_ID, P14C_CLIENT_SECRET
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingaccess-was-passwords

---
