apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "ping-cloud-${CLUSTER_STATE_REPO_BRANCH}-${TENANT_NAME}-${REGION_NICK_NAME}"
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: ${CLUSTER_STATE_REPO_URL}
        revision: ${CLUSTER_STATE_REPO_BRANCH}
        directories:
          - path: ${REGION_NICK_NAME}/*
  template:
    metadata:
      name: '${REGION_NICK_NAME}-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: ${CLUSTER_STATE_REPO_URL}
        targetRevision: ${CLUSTER_STATE_REPO_BRANCH}
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
      ignoreDifferences:
        - group: batch
          kind: Job
          jsonPointers:
            - /spec/ttlSecondsAfterFinished
      syncPolicy:
        automated:
          prune: true