apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elasticsearch-sc1
  labels:
    app: elasticsearch
provisioner: kubernetes.io/aws-ebs
parameters:
  encrypted: "true"
  type: sc1
  fsType: ext4
mountOptions:
  - discard
allowVolumeExpansion: true