# Add an "argocd" Namespace for all namespace-scoped resources
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
# Add an "argo-git-deploy" Secret to hold the SSH key for git cloning
apiVersion: v1
kind: Secret
metadata:
  name: argo-git-deploy
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    managed-by: argocd.argoproj.io
type: Opaque
